version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    deploy:
      replicas: 1
      update_config:
        parallelism: 1  # update 1 instance at a time
        delay: 2s  # wait 2 seconds between updates
        order: start-first # start the new task before stopping the old one
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - lms_network

networks:
  lms_network:
    external: true