@startuml
autoactivate on
autonumber

title Register a new book as librarian

actor "Anonymous" as Anonymous
participant ":System" as System
participant "Ctrl:BookController" as Ctrl
participant "service:BookService" as Service
participant "repo:BookRepository" as RepoInterface
participant "repoImpl:MongoBookRepository / JPABookRepository" as RepoImpl
participant "mapper:BookMapper" as Mapper
participant "book:Book" as Book
participant "dataModel:JPABook / MongoBook" as DataModel

activate Anonymous

Anonymous -> System: requests book registration based on given data

System -> Ctrl: registerBook(RegisterBookRequest)

Ctrl -> Service: create(title, isbn, ...)
Service -> Book: Book(title, isbn, ...)
Service --> Ctrl: Book or exception

alt If exception is returned
    Ctrl -> System: Book is duplicate
end

Ctrl -> Service: save(book)

' Using BookMapper to map Book to JPABook or MongoBook
Service -> Mapper: map Book to JPABook / MongoBook
Mapper --> Service: JPABook / MongoBook object

Service -> RepoImpl: save(JPABook / MongoBook)
RepoImpl --> Service: JPABook / MongoBook or exception

' Convert back to domain model if needed
Service -> Mapper: map JPABook / MongoBook to Book
Mapper --> Service: Book or exception

Service --> Ctrl: Book or exception

Ctrl --> System: Book or exception
System --> Anonymous: registered book

@enduml

