spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 985639279866-lnjk08cag76mukdshh58pgj4aqh08e31.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: http://localhost:8080/api/oauth2/callback
            client-name: Google
          facebook:
            client-id: YOUR_FACEBOOK_APP_ID
            client-secret: YOUR_FACEBOOK_APP_SECRET
            scope: email, public_profile
            redirect-uri: http://localhost:8080/api/oauth2/callback
            client-name: Facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            authorization-uri: https://www.facebook.com/v12.0/dialog/oauth
            token-uri: https://graph.facebook.com/v12.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email

