
services:
    lmsmiscs_1:
        image: lmsmiscs:latest
        container_name: miscs1_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8089:8083"
        env_file:
            - MY_ENV_VARS.env
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap,jpa,google,hash,genre_based
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"

    lmsmiscs_2:
        image: lmsmiscs:latest
        container_name: miscs2_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8090:8083"
        env_file:
            - MY_ENV_VARS2.env
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap,jpa,google,hash,genre_based
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2: