
services:
    lmslendings_1:
        image: lmslendings:latest
        container_name: lendings1_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8087:8083"
        env_file:
            - MY_ENV_VARS.env
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap,jpa,google,hash,genre_based
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_1:/tmp"

    lmslendings_2:
        image: lmslendings:latest
        container_name: lendings2_in_lms_network
        build:
            context: ..
            dockerfile: Dockerfile
        ports:
            - "8088:8083"
        env_file:
            - MY_ENV_VARS2.env
        environment:
            SPRING_PROFILES_ACTIVE: bootstrap,jpa,google,hash,genre_based
        networks:
            - lms_network
        volumes:
            - "uploaded_files_volume_2:/tmp"

networks:
    lms_network:
        external: true

volumes:
    uploaded_files_volume_1:
    uploaded_files_volume_2: